Add mailing list to placeholder site
sbhacks-org/sbhacks-site pull request #1
Opened 2020-09-20 20:39 UTC by btk5h

2020-09-20 21:00 UTC, jay-red approved these changes
Looks good!

2020-09-20 22:04 UTC, tshiUCSB requested changes
Great job but just a number of stylistic things that would be nice to alter:

- decrease the font size for "Subscribe to our mailing list for updates!"
- add text that displays "Successfully added to mailing list", "Email already exists in mailing list", or "Unable to add to mailing list" on submission (since there's more space on top of the logo, it might be better to add it on top?)
- increase the size for input field and bottle button
- give a bit more padding/margin to the top of the input field
- autofocus on input field
- change cursor for bottle to pointer
- bottle is normally lower opacity (abt .6?)
- bottle on hover is full opacity and enlarges for responsiveness, also add alt text "submit"
- bottle on active is back to original size to give the feeling of a click
- for mobile, make the bottle larger and stack it below the input field with both of them horizontally centered since mobile typically have larger buttons for easy pressing

Sorry that there's a good number of things that could've been better specified. Many of them are details that are quick fixes
Lmk if any of them is unclear

2020-09-22 00:19 UTC, jay-red approved these changes

2020-09-22 00:54 UTC, tshiUCSB commented
@btk5h thank you, everything looks good!
Just add these css changes and I think we're ready to go:
#message {
    font-size: 24px;
    padding: 24px;
    position: relative;
    z-index: 400;
}
#landing {
    background-image: url(/webAssets/Asset 15.svg);
    background-size: cover;
    background-position: center;
    width: 100vw;
    height: 100vh;
    position: relative;
    overflow: hidden;
    min-height: 700px;
    top: -78px;
}

2020-09-22 01:03 UTC, tshiUCSB approved these changes

2020-09-23 03:46 UTC, merged